version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 99
  target-branch: 06-fuzziness
  reviewers:
  - dadoonet
  assignees:
  - dadoonet
  ignore:
  - dependency-name: org.elasticsearch:elasticsearch
    versions:
    - 7.10.2
    - 7.11.0
    - 7.11.1
    - 7.11.2
  - dependency-name: org.elasticsearch.client:elasticsearch-rest-client
    versions:
    - 7.10.2
    - 7.11.0
    - 7.11.1
    - 7.11.2
  - dependency-name: org.elasticsearch.client:elasticsearch-rest-high-level-client
    versions:
    - 7.10.2
    - 7.11.0
    - 7.11.1
    - 7.11.2
  - dependency-name: com.fasterxml.jackson.core:jackson-annotations
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.core:jackson-core
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.2
    - 2.4.3
